version: "3.8"

services:
  mysqldb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ekenesql
      - MYSQL_DATABASE=clustereddata
    networks:
      - fx_deals

  clustered-data_warehouse:
    image: fx-deals/app:0.0.1
    ports:
      - "5300:5200"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 120s
    depends_on:
      - mysqldb
    environment:
      DB_URL: jdbc:mysql://192.168.0.187:3307/clustereddata?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      DRIVER_CLASS: com.mysql.jdbc.Driver
    networks:
      - fx_deals

networks:
  fx_deals: